// @generated by Stately. DO NOT EDIT.
/* eslint-disable */

import {
  createClient as createGenericClient,
  makeCreateFunction,
  
} from "@stately-cloud/client";
import {
  ChannelSchema,
  CharacterSchema,
  ShowSchema,
} from "./stately_pb.js";

export const typeToSchema = {
  // itemTypes
  "Channel": ChannelSchema,
  "Character": CharacterSchema,
  "Show": ShowSchema,

  // objectTypes
};


/** The version of the schema that this client was generated for. */
export const SCHEMA_VERSION_ID = 1;
export const SCHEMA_ID = 1306304359835540;


export function createClient({ storeId, transport, ...transportOptions }) {
  
  return createGenericClient({
    storeId,
    itemTypeMap: typeToSchema,
    schemaVersionID: SCHEMA_VERSION_ID,
    schemaID: SCHEMA_ID,
    clientFactory: transport(transportOptions),
  });
  
}

export const create = makeCreateFunction(typeToSchema);

if (createGenericClient.length !== 1) {
  throw new Error("Your version of @stately-cloud/client is too old. Please update to the latest version.");
}
