// @generated by Stately. DO NOT EDIT.
/* eslint-disable */

import type {GenFile,
  GenMessage,
  ProtobufESMessage,
} from "@stately-cloud/client";

export declare const file_stately: GenFile;

/**
 * These items can be accessed via the following key paths:
 *   * /channel-:channelId
 */
export declare type Channel = ProtobufESMessage<"stately.generated.Channel"> & {
  channelId: Uint8Array;
  name: string;
  description: string;
  createdAt: bigint;
  updatedAt: bigint;
};

/**
 * Describes the message stately.generated.Channel.
 * Use `create(ChannelSchema)` to create a new message.
 */
export declare const ChannelSchema: GenMessage<Channel>;

/**
 * These items can be accessed via the following key paths:
 *   * /character-:characterId
 *   * /channel-:channelId/show-:showId/character-:characterId
 */
export declare type Character = ProtobufESMessage<"stately.generated.Character"> & {
  channelId: Uint8Array;
  showId: Uint8Array;
  characterId: Uint8Array;
  name: string;
  role: string;
  description: string;
  createdAt: bigint;
  updatedAt: bigint;
};

/**
 * Describes the message stately.generated.Character.
 * Use `create(CharacterSchema)` to create a new message.
 */
export declare const CharacterSchema: GenMessage<Character>;

/**
 * These items can be accessed via the following key paths:
 *   * /show-:showId
 *   * /channel-:channelId/show-:showId
 */
export declare type Show = ProtobufESMessage<"stately.generated.Show"> & {
  channelId: Uint8Array;
  showId: Uint8Array;
  title: string;
  description: string;
  year: string;
  createdAt: bigint;
  updatedAt: bigint;
};

/**
 * Describes the message stately.generated.Show.
 * Use `create(ShowSchema)` to create a new message.
 */
export declare const ShowSchema: GenMessage<Show>;