// @generated by Stately. DO NOT EDIT.
/* eslint-disable */

import {
  fileDesc,
  messageDesc,} from "@stately-cloud/client";


export const file_stately =
  /*@__PURE__*/
  fileDesc("Cg1zdGF0ZWx5LnByb3RvEhFzdGF0ZWx5LmdlbmVyYXRlZCKlAQoHQ2hhbm5lbBIeCgljaGFubmVsSWQYASABKAxCAFIJY2hhbm5lbElkEhQKBG5hbWUYAiABKAlCAFIEbmFtZRIiCgtkZXNjcmlwdGlvbhgDIAEoCUIAUgtkZXNjcmlwdGlvbhIeCgljcmVhdGVkQXQYBCABKBJCAFIJY3JlYXRlZEF0Eh4KCXVwZGF0ZWRBdBgFIAEoEkIAUgl1cGRhdGVkQXQ6ACL7AQoJQ2hhcmFjdGVyEh4KCWNoYW5uZWxJZBgBIAEoDEIAUgljaGFubmVsSWQSGAoGc2hvd0lkGAIgASgMQgBSBnNob3dJZBIiCgtjaGFyYWN0ZXJJZBgDIAEoDEIAUgtjaGFyYWN0ZXJJZBIUCgRuYW1lGAQgASgJQgBSBG5hbWUSFAoEcm9sZRgFIAEoCUIAUgRyb2xlEiIKC2Rlc2NyaXB0aW9uGAYgASgJQgBSC2Rlc2NyaXB0aW9uEh4KCWNyZWF0ZWRBdBgHIAEoEkIAUgljcmVhdGVkQXQSHgoJdXBkYXRlZEF0GAggASgSQgBSCXVwZGF0ZWRBdDoAItQBCgRTaG93Eh4KCWNoYW5uZWxJZBgBIAEoDEIAUgljaGFubmVsSWQSGAoGc2hvd0lkGAIgASgMQgBSBnNob3dJZBIWCgV0aXRsZRgDIAEoCUIAUgV0aXRsZRIiCgtkZXNjcmlwdGlvbhgEIAEoCUIAUgtkZXNjcmlwdGlvbhIUCgR5ZWFyGAUgASgJQgBSBHllYXISHgoJY3JlYXRlZEF0GAYgASgSQgBSCWNyZWF0ZWRBdBIeCgl1cGRhdGVkQXQYByABKBJCAFIJdXBkYXRlZEF0OgBiBnByb3RvMw==");

/**
 * Describes the message stately.generated.Channel.
 * Use `create(ChannelSchema)` to create a new message.
 */
export const ChannelSchema = /*@__PURE__*/ messageDesc(file_stately, 0);


/**
 * Describes the message stately.generated.Character.
 * Use `create(CharacterSchema)` to create a new message.
 */
export const CharacterSchema = /*@__PURE__*/ messageDesc(file_stately, 1);


/**
 * Describes the message stately.generated.Show.
 * Use `create(ShowSchema)` to create a new message.
 */
export const ShowSchema = /*@__PURE__*/ messageDesc(file_stately, 2);
